tellstickNetIp: 192.168.2.1
logLevel: debug
mqtt:
  enabled: false
  host: localhost
  port: 1883    
devices:
  - name: TD_S_1
    type: switch
    protocol: arctech
    model: selflearning
    parameters:
      - house: 6008049
        unit: 1
      - house: 45362
        unit: 16
  - name: Cotech_1
    type: switch
    protocol: text
    parameters:
      - on: "&\xe1p%%p%pp%%pp%p%p%%pp%%pp%p%%p%pp%%pp%%p%p%p%p%p%p"
        off: "&\xe1p%%p%pp%%p%p%pp%p%%pp%p%%pp%%p%pp%%pp%%p%p%p%p%p"
        pause: 0


